name: EnSF-GMM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - pip
  - pip:
    - -e .  # This installs local packages from pyproject.toml